apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'jolokia'
        static_configs:
          - targets: ['jolokia-exporter-service:9779']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter-service:9100']
