apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-jolokia
  namespace: default
  labels:
    app: jenkins-jolokia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-jolokia
  template:
    metadata:
      labels:
        app: jenkins-jolokia
    spec:
      containers:
      - name: jenkins-container
        image: jenkins-jolokia:v4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-jenkins
          containerPort: 8080
        - name: http-jolokia
          containerPort: 8778
        - name: http-metrics
          containerPort: 9404
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
